### ISSUE TITLE
Recipe changing through datapack is not working

### ISSUE THREAD

**Issue by WelpSTudent** [0999312/Corn-Delight#13]
I am trying to change the recipes and it will not work. I think there is an error on your end since you are the only mod I am having trouble with doing so

**Comment by 0999312** [comment]
Is there a log or something?

**Comment by WelpSTudent** [comment]
Not really no, you can try it by changing a recipe through datapack, in my case I was doing it with the crate recipe an replacing the corn with a nether star, nothing was changing in game after a reload

**Comment by 0999312** [comment]
Version and more infomation please.
