### ISSUE TITLE
Various recipe issues

### ISSUE THREAD

**Issue by chopspry** [0999312/Corn-Delight#17]
Cornbread stuffing has 9 bars of hunger and 18 saturation, while the corn dog made out of it has 4 hunger and 7.5 saturation.
![image](https://user-images.githubusercontent.com/69838357/163987379-a8f6bff3-e6c4-4958-b398-1dd21b14bfcf.png)
![image](https://user-images.githubusercontent.com/69838357/163987399-23186132-665b-46d8-bdae-2e3fd49361d1.png)

Tortilla chips no longer have a recipe (no picture but the chopping board recipe broke)

Stuffed pumpkin has 2 identical recipes
![image](https://user-images.githubusercontent.com/69838357/163987587-7390049e-113d-47ad-8105-e9f07cd9b0bb.png)

there are 2 recipes for raw tortillas with create
![image](https://user-images.githubusercontent.com/69838357/163987740-1757b127-11c2-47d3-9867-98ba93d40493.png)

Very good mod, just wanted to bring awareness to some of these minor issues that seem to have come from the lastest update.

**Comment by MarioSMB** [comment]
Stuff pumpkin isn't the only recipe duplicated by being copied to the Minecraft data subspace; corn_seeds_from_bag and corn_from_crate are also present there causing duplicate recipes with Minecraft as the recipe source.

**Comment by MarioSMB** [comment]
Should be safe to close this one now!
