### ISSUE TITLE
[Upcoming issue] Datapack load error with FD 0.6/1.1

### ISSUE THREAD

**Issue by vectorwing** [0999312/Corn-Delight#19]
Hi there! 😄 

This issue is mostly a heads-up regarding changes to an **upcoming** release of FD, **0.6** (1.16) and **1.1** (1.18).

It seems Corn Delight is consulting FD's internal configs to determine whether to generate corn in shipwrecks and village houses. Due to the addition of several new chest loot modifications, I have recently **removed** these configs, substituting them for a universal `generateFDChestLoot` key.

This causes the current version to suffer a datapack load error, as shown in the logs below.

Though I understand why it was done, I don't recommend basing your add-on's features around FD's configs directly, as those are subject to minor changes. Might be better to have your own separate config here.

Sorry for the inconvenience! 😓

### Logs:

https://pastebin.com/yYYmFzNQ

**Comment by 0999312** [comment]
Roger that, thanks.

**Comment by 0999312** [comment]
1.18.2 Now Finished
