### ISSUE TITLE
1.18.2 - Tortilla Chip has no recipe in game

### ISSUE THREAD

**Issue by blob1807** [0999312/Corn-Delight#22]
Tortilla can't be be cut into Tortilla Chips.
JEI also says no recipe for it.

MC - 1.18.2
Forge - 40.1.0
Launcher - MultiMC 5
Corn Delight - 1.0.2-1.18.2
MMLib - 1.0.1-1.18.2
Farm's Delight - 1.18.2-1.1.0

![Issue](https://i.imgur.com/ePgwRdZ.png)
![Mod Version](https://i.imgur.com/aLKVdkM.png)

**Comment by 0999312** [comment]
Fixed
