### ISSUE TITLE
[Suggestion] Link to Issues from CurseForge

### ISSUE THREAD

**Issue by MarioSMB** [0999312/Corn-Delight#29]
A link to the Issues page from CurseForge where Files and Source are displayed would be great, thanks!

**Comment by MarioSMB** [comment]
I took a look at the main page and this doesn't appear to be resolved.  

A majority of mods provide a direct link to issues, it would be appreciated if this mod could do the same.

**Comment by 0999312** [comment]
Sorry that, added.
