### ISSUE TITLE
[Suggestion] Change the recipe for raw tortilla to use water bottles instead of water buckets

### ISSUE THREAD

**Issue by skrollas** [0999312/Corn-Delight#31]
Right now, it is extremely annoying to craft raw tortillas with water buckets unless you have several of them in your inventory (which is also not ideal since they're unstackable and take up a lot of space), as you will have to keep refilling the bucket each time you make the recipe. For a QoL change, I strongly suggest changing the current recipe to use water bottles instead of buckets, as they are stackable to 16 and are much less of a hassle to craft with as a result.

**Comment by MarioSMB** [comment]
Most mods dealing with food tend to require buckets of water for crafting the "washed" variants, as water bottles are mostly an alchemy component.
