### ISSUE TITLE
[COL] Crash after updating to Farmer's Delight 1.2

### ISSUE THREAD

**Issue by drakray** [0999312/Corn-Delight#35]
Minecraft 1.18.2
Forge 40.1.80
Farmer's Delight 1.2
Corn Delight 1.0.5

Crash don't mention it directly, but going back in debug.log show this https://pastebin.com/XsbmPqMH
After that everything goes south and fail to load
Full [latest.log](https://github.com/0999312/Corn-Delight/files/9621244/latest.log)
Pastebin part start at line ~1713

**Comment by drakray** [comment]
Removing Corn Delight from the pack allow everything to load normally

**Comment by 0999312** [comment]
Fixing, please wait.

**Comment by 0999312** [comment]
Fixed, wait for CF Update.
