### ISSUE TITLE
You require a lib that does not function.

### ISSUE THREAD

**Issue by MagmaBro123** [0999312/Corn-Delight#36]
Title. Whatever 'mmlib' is, it crashes the game. Even on its own.

https://pastebin.com/eMUpA0Sf

**Comment by MagmaBro123** [comment]
Never mind. I'm an idiot.

Don't know why MidnightLib and Mysterious Mountain Lib both have the same mod ID in-game. Really confusing.

**Comment by 0999312** [comment]
Seriously? MidnightLib and Mysterious Mountain Lib both have the same mod ID???

**Comment by MagmaBro123** [comment]
yEP.

**Comment by 0999312** [comment]
Well, I will change Mysterious Mountain Lib's modid next update.

**Comment by 0999312** [comment]
Sorry for long time, updated and fixed now.
