### ISSUE TITLE
[1.19.x and 1.20.1] Modrinth parity

### ISSUE THREAD

**Issue by ColonelGerdauf** [0999312/Corn-Delight#42]
There is an update a while ago supporting 1.20.1 in Curseforge.
Yet, in Modrinth, the latest remains 1.18.

Is there any intention to update in Modrinth, or is there a reason to focus on Curseforge?

**Comment by 0999312** [comment]
oh sorry, forget about that.
update soon

**Comment by 0999312** [comment]
Now updated, sorry for late
