### ISSUE TITLE
No Recipes? 1.21.1

### ISSUE THREAD

**Issue by StoneLegion** [0999312/Corn-Delight#49]
corn_delight-1.0.1-1.21.1.jar

Nothing has a single recipe.

Thanks.

**Comment by DracoHero** [comment]
I confirm, wild plants do not give their seeds too

**Comment by 0999312** [comment]
Fixing on road, soon.

**Comment by OleGray** [comment]
"I'M WAITING WITH ANTICIPATION. I REALLY WANT TO TRY THIS MOD.

**Comment by 0999312** [comment]
FIXED in new version.
