### ISSUE TITLE
Game crashes when trying to open a chest.

### ISSUE THREAD

**Issue by OleGray** [0999312/Corn-Delight#50]
The game crashes when I try to loot a chest while using these mods. Could you help me understand the issue?
[crash-2024-10-24_17.12.40-server.txt](https://github.com/user-attachments/files/17517399/crash-2024-10-24_17.12.40-server.txt)

**Comment by 0999312** [comment]
Fixing on the road

**Comment by 0999312** [comment]
Fixed in Mysterious Mountain Lib 1.1.8-1.21.1
